### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by mister-good-deal** [eco-transports-campus/naiveco2calculatorModule#1]
Put the npm URL to install the module in the `README.md`

You have to publish your package with `npm publish` before.

Delete `package-lock.json` from this repo.

Put jsDoc functions documentation for `degreesToRadians` and `distanceInKmBetweenEarthCoordinates` like you did for the others functions (and you did it well !).

Try to use `const` instead of `var` to be ES6 compliant everywhere in your code.

**Comment by Thierry-girard** [comment]
Done.
